import React from "react";

function ProjectData(){


return (
    <div className="project-data">
        <div className="project-desc">
            <div>
            <h1>Project Description</h1>
            </div>
            <div>
            <p>DataPipe is a project that implements three ETL (Extract, Transform, Load) pipelines for processing dynamic data which is been generating dynamically from an e-commerce website. In this project a advanced library named "generate_data_library" is created to generate data which is almost similar to that of generated by a ecommerce website.</p>
            </div>
        </div>
        <div className="project-info">

            <h3>Project Information</h3>
            <div className="project-info-data">
                <div className="info-list">
                    <p>TITLE</p>
                    <p>ETL Pipeline for E-Commerce Data</p>
                </div>
                <div className="info-list">
                    <p>TECH STUFF USED</p>
                    <p>SQL, Python, Basics of OOPS, Threading</p>
                </div>
                <div className="info-list">
                    <p>PROJECT URL</p>
                    <p className="project-url">Github Repo</p>
                </div>
            </div>

        </div>

    </div>
)
}

export default ProjectData;